---
title: Gareth Johns Design + Development
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: false
url: http://garethjohnsdesign.com
description: A London-based studio focused on art direction, development, and design
  for print.
permalink: pretty
exclude:
- Gemfile
- Gemfile.lock
- bower.json
- package.json
- config.codekit3
- README*
- LICENSE*
- CHANGELOG*
- node_modules
- ".gitignore"
- bower_components
- assets/scss
gems:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
colophon: http://garethjohnsdesign.com
company: Gareth Johns Design + Development
email: info@garethjohnsdesign.com
phone-number: "+44(0)77 2573 7734"
address-text: "Unit D  \n100 De Beauvoir Road  \nLondon N1 4EN"
map: https://goo.gl/maps/GYrrK5YHjmP2
google_site_verification: gVB2Kp0p50x6bj4fZ7ryqYCRefN8GQGzSxZPI86fKGI
analytics: UA-55680721-1
logo: "/assets/img/logo.svg"
per_page: 12
date_format: "%d %B %Y"
future: true
social:
  facebook: https://www.facebook.com/
  instagram: https://www.instagram.com/
  twitter: https://www.twitter.com/
  linkedin: https://www.linkedin.com/in/
compress_html:
  comments:
  - "<!-- "
  - " -->"
  blanklines: true
  profile: false
